### PR TITLE
docs: fix npx example

### PR DESCRIPTION
**Pull request by revolunet**
Hi, looks like we need `npx hasura-cli`

before :
Capture d’écran 2022-12-26 à 14 09 50

after:
Capture d’écran 2022-12-26 à 14 10 54

PS: thanks a ton for this handy tool !

### CODE REVIEW

**Comment by jjangga0214** [comment]
Thank you for the report!
Well, for majority of people are OK with `hasura`. 
Actually, for them, `hasura-cli` would cause error.
I believe you're in a specific situation.
Would you please share your environment?
For example, OS, CLI version, nodejs version, whether you use IDE-integrated terminal (e.g. vscode's) or not, whether you're using WSL, etc.

**Comment by revolunet** [comment]
Hello, using npm@16 on OSX

when you call `npx hasura` it try to fetch the npm package named hasura` which is another beast and an empy package

**Comment by jjangga0214** [comment]
@revolunet Ah, now I think I understand why.

You should execute `npx hasura` AFTER the installation.
For example,

```sh
npm install --save-dev hasura-cli
npx hasura version
```

If you execute `npx hasura` BEFORE the installation, then the `npx` tries to install the package `hasura` (which is the other one) and execute it. This is why it DOES NOT work.

And, if you execute `npx hasura-cli` BEFORE the installation, then the `npx` tries to install the package `hasura-cli` (which is the right one) and execute it. This is why it DOES work. 

I intentionally set the entrypoint name `hasura`, not `hasura-cli`, though the package name is `hasura-cli`.
That's because the original binary's entrypoint name is also `hasura`. I want people to experience consistency.

Thanks for the report anyway. 
I'd like to close this right now. 
But if you still have an issue or question, feel free to reopen anytime.

Thanks :)

**Comment by revolunet** [comment]
as `npx hasura-cli` always work i think its less confusing to document this way. 

Your call by the way, thanks for this package !

**Pull request closed without merging**
