### PR TITLE
chore(release): v2.0.0-alpha.8

### PR DESCRIPTION
**Pull request by zenflow**
New v2 alpha prerelease: https://github.com/hasura/graphql-engine/releases/tag/v2.0.0-alpha.8

### CODE REVIEW

**Comment by zenflow** [comment]
Pretty sure the CI failure is not related to the change:

```
Run yarn add --ignore-scripts --ignore-engines -D typescript shx
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.6.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/hasura-cli/hasura-cli/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Process completed with exit code 1.
``` 

I'm guessing that triggering CI again will fix the CI status for the commit

**Comment by zenflow** [comment]
@jjangga0214 The next v2 alpha version (`v2.0.0-alpha.9`) was released today.. I guess this should be merged first and then that next version can be released, so that `v2.0.0-alpha.8` is still available in case someone needs that specific version for some reason, right?

**Comment by zenflow** [comment]
@jjangga0214 After triggering tests 3 more times (by force-pushing different commits with exact same content) the CI is passing 

We kept getting the same failure as the initial failure I mentioned (i.e. https://github.com/jjangga0214/hasura-cli/pull/59#issuecomment-824541770).. Really I have no idea why this would be happening sometimes.. 🤷

**Comment by zenflow** [comment]
@jjangga0214 Please click merge 😃  Yesterday `v2.0.0-alpha.10` was released. We're falling behind ☹️

**Comment by jjangga0214** [comment]
@zenflow Thank you so much!
I sincerely apologize for being late.
Thanks again!

**Comment by zenflow** [comment]
@jjangga0214 It's my pleasure to make this tiny contribution! No need to apologize whatsoever.. you don't owe me/us anything and we are grateful the project exists! Besides, if we really urgently needed the new versions we could fork and publish!

Regarding the flaky CI.. It's a good puzzle. I was wondering if GitHub Actions has some kind of limit on network traffic that we are running into due to the large number of jobs in the job matrix (6 * 4 = 24) but I couldn't find any documentation of that (not [here](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) anyways). I still have a feeling (fwiw) that the high number of jobs might have something to do with the CI flakiness. That said, do we need to test against old versions of Node.js that aren't supported [by the Node.js team] anymore? I mean versions 8, 9, 10, 11, & 13. See https://nodejs.org/en/about/releases/. What do you think about removing these from the test matrix? We should probably also add the newer "active" & "current" versions: 14, 15 (soon to be unsupported) & 16. If we removed the 5 unsupported versions and added the 3 new versions, going from testing against 6 Node.js versions to 4, we would reduce the load by 1/3.

**Comment by zenflow** [comment]
@jjangga0214 Oh! And thank you for catching us up on releases today! 🙏

**Comment by jjangga0214** [comment]
@zenflow 

> due to the large number of jobs in the job matrix

Good point! I agree.

I patched the `node-version` in 456f0c773b77bf9537ced555b5fc3fa95da4731e.
https://github.com/jjangga0214/hasura-cli/blob/f29c1e9d9c70b435544d47f7f2978e5b8ebd6f11/.github/workflows/test-publish.yml#L91-L92

It seems it works at least for now.
Let's see if a similar issue would appear in future :)

**Pull request merged**
